### ISSUE TITLE
Failed while running bootstrap analysis

### ISSUE THREAD

**Issue by annarerra** [nickjcroucher/gubbins#312] opened 2021-10-15 12:38 UTC
Hello,

I am running gubbins with this command:
run_gubbins.py --first-tree-builder fasttree --first-model JC --tree-builder fasttree --model JC core_gene_alignment.aln --bootstrap 100 --transfer-bootstrap --verbose --threads 5

but i am receiving an error message: **Failed while running bootstrap analysis**

I would appreciate any help.

Thank you in advance :)

**Comment by nickjcroucher** [comment] 2021-10-16 08:55
Using the ST239.aln example, this command worked fine for me:
`run_gubbins.py --first-tree-builder fasttree --first-model JC --tree-builder fasttree --model JC --bootstrap 100 --transfer-bootstrap --verbose ST239.aln`

This is with:
- gubbins v3.1.2 (shows up as 3.1.1, due to a typo, sorry)
- RAxML-NG v. 1.0.1
- RAxML v8.2.12
- fasttree 2.1.1

Do your versions match?

**Comment by annarerra** [comment] 2021-10-17 19:33
Hello,

Thank you for your answer :)
My version of gubbins is the 3.0.0.
I changed it to 3.1.1 (3.1.2) but i have still the issue :/

"No sequence in phylip line ..
Failed while running bootstrap analysis."

**Comment by nickjcroucher** [comment] 2021-11-08 20:51
Sorry, I thought this was resolved - what do the header lines of your FASTA alignment look like?

**Comment by annarerra** [comment] 2021-11-08 21:21
Hello,

They look like this
![image](https://user-images.githubusercontent.com/74925521/140820070-2dceb97d-69a0-4bae-a70a-21f8cace88e0.png)

**Comment by nickjcroucher** [comment] 2021-11-08 21:23
That one looks fine - does your analysis work with an example alignment, e.g. ftp://ftp.sanger.ac.uk/pub/project/pathogens/gubbins/ST239.aln.gz?

**Comment by annarerra** [comment] 2021-11-09 08:23
I can try with this and let you know..

Thank you again :)

**Comment by annarerra** [comment] 2021-11-09 08:50
So i used this command: _run_gubbins.py --first-tree-builder fasttree --first-model JC --tree-builder fasttree --model JC ST239.aln --bootstrap 100 --transfer-bootstrap --verbose --threads 5_ and it worked of course.

When using this command: _run_gubbins.py -s core_gene_alignment.newick -t fasttree --bootstrap 100 --transfer-bootstrap --verbose ST239.aln -c 5_  it doesnt work because of different names of tree and alignment..

But still we dont have an insight about the error that i usually get:
![image](https://user-images.githubusercontent.com/74925521/140892404-84374823-53e9-4a46-852f-cf159870f541.png)

**Comment by nickjcroucher** [comment] 2021-11-09 09:01
It is helpful to know Gubbins is running OK on your machine with a validated alignment. Do you see an error without the transfer bootstrap (i.e. `run_gubbins.py --first-tree-builder fasttree --first-model JC --tree-builder fasttree --model JC core_gene_alignment.aln --bootstrap 100 --verbose --threads 5`) and without any bootstrap (i.e. `run_gubbins.py --first-tree-builder fasttree --first-model JC --tree-builder fasttree --model JC core_gene_alignment.aln --verbose --threads 5`)?

**Comment by annarerra** [comment] 2021-11-09 13:56
Without the transfer bootstrap I have the same error as before.
WIthout any boostrap is working, but i really need to add the bootstrap values. There are other ways to do it as well, but i think gubbins way is more accurate. And actually for iqtree and raxml tree, with the same alignment file, bootstrap is working, but not for the fasttree :/

**Comment by nickjcroucher** [comment] 2021-11-09 15:16
If you are able to email me a subset of your data, that reproduces the error, I can take a look if helpful?

**Comment by annarerra** [comment] 2021-11-09 15:28
I just sent you an email at the imperial address.

Thank you again :)

**Comment by nickjcroucher** [comment] 2021-11-10 12:37
Thanks - the issue is with writing bootstrapped alignments to the phylip format - strictly, this is limited to names of ten characters, then the sequence follows directly afterwards. It seems as though RAxML and Fasttree disagree on how strictly to follow these rules. I've changed to using biopython to bootstrap the alignments in 0b4a955, and I'll get this released as part of a general update soon.

**Comment by annarerra** [comment] 2021-11-10 12:45
I see.. Ok then, I will wait and try afterwards..

Thanks again for everything :)

**Comment by nickjcroucher** [comment] 2021-11-15 11:38
Addressed in release v3.1.4 - should be on bioconda soon.

**Closed as completed by nickjcroucher** 2021-11-15 11:38 UTC
